In [1]:
import numpy as np
import scipy.linalg.blas as slb
from scipy.spatial.distance import cdist, pdist

In [2]:
def distance_2(A):
    dists = np.zeros((A.shape[0],A.shape[0]))
    for i in range(A.shape[0]):
        u = A[i,:]
        A_adj = A.copy()
        A_adj[:,0] = A_adj[:,0] - u[0]
        A_adj[:,1] = A_adj[:,1] - u[1]
        A_adj[:,2] = A_adj[:,2] - u[2]
        A_adj = A_adj*A_adj
        dists[i,:] = A_adj[:,0] + A_adj[:,1] + A_adj[:,2]
    return dists

In [3]:
# Heronian triangle edge lengths
locations = np.array([[0,0,0],[3,4,5],[6,5,5],[8,5,5],[15,13,4]])
locations

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [ 6,  5,  5],
       [ 8,  5,  5],
       [15, 13,  4]])

In [4]:
distance_2(locations)

array([[  0.,  50.,  86., 114., 410.],
       [ 50.,   0.,  10.,  26., 226.],
       [ 86.,  10.,   0.,   4., 146.],
       [114.,  26.,   4.,   0., 114.],
       [410., 226., 146., 114.,   0.]])

In [5]:
cdist(locations, locations, metric='sqeuclidean')

array([[  0.,  50.,  86., 114., 410.],
       [ 50.,   0.,  10.,  26., 226.],
       [ 86.,  10.,   0.,   4., 146.],
       [114.,  26.,   4.,   0., 114.],
       [410., 226., 146., 114.,   0.]])

In [6]:
pdist(locations, metric='sqeuclidean')

array([ 50.,  86., 114., 410.,  10.,  26., 226.,   4., 146., 114.])

## n = 500

In [7]:
np.random.seed(0)
A = np.random.rand(500,3)

In [8]:
%%time
for i in range(100):
    a = distance_2(A)

CPU times: user 1.32 s, sys: 7.47 ms, total: 1.33 s
Wall time: 1.33 s


In [9]:
%%time
for i in range(100):
    a = cdist(A, A, metric='euclidean')

CPU times: user 172 ms, sys: 19.9 ms, total: 192 ms
Wall time: 191 ms


In [10]:
%%time
for i in range(100):
    a = pdist(A, metric='euclidean')

CPU times: user 82.7 ms, sys: 0 ns, total: 82.7 ms
Wall time: 83.4 ms


In [11]:
%%time
for i in range(100):
    a = cdist(A, A, metric='sqeuclidean')

CPU times: user 85.1 ms, sys: 3.91 ms, total: 89 ms
Wall time: 87.7 ms


In [12]:
%%time
for i in range(100):
    a = pdist(A, metric='sqeuclidean')

CPU times: user 41.7 ms, sys: 69 µs, total: 41.8 ms
Wall time: 40.6 ms


## n = 1000

In [13]:
np.random.seed(0)
A = np.random.rand(1000,3)

In [14]:
%%time
for i in range(20):
    a = distance_2(A)

CPU times: user 709 ms, sys: 3.98 ms, total: 713 ms
Wall time: 713 ms


In [15]:
%%time
for i in range(20):
    a = cdist(A, A, metric='euclidean')

CPU times: user 111 ms, sys: 40 ms, total: 151 ms
Wall time: 149 ms


In [16]:
%%time
for i in range(20):
    a = pdist(A, metric='euclidean')

CPU times: user 65.7 ms, sys: 79 µs, total: 65.8 ms
Wall time: 64.3 ms


In [17]:
%%time
for i in range(20):
    a = cdist(A, A, metric='sqeuclidean')

CPU times: user 85.5 ms, sys: 16.1 ms, total: 102 ms
Wall time: 102 ms


In [18]:
%%time
for i in range(20):
    a = pdist(A, metric='sqeuclidean')

CPU times: user 34.6 ms, sys: 3.74 ms, total: 38.3 ms
Wall time: 37 ms


## n = 2000

In [19]:
np.random.seed(0)
A = np.random.rand(2000,3)

In [20]:
%%time
for i in range(10):
    a = distance_2(A)

CPU times: user 963 ms, sys: 40 ms, total: 1 s
Wall time: 1 s


In [21]:
%%time
for i in range(10):
    a = cdist(A, A, metric='euclidean')

CPU times: user 240 ms, sys: 43.9 ms, total: 284 ms
Wall time: 283 ms


In [22]:
%%time
for i in range(10):
    a = pdist(A, metric='euclidean')

CPU times: user 117 ms, sys: 8.08 ms, total: 126 ms
Wall time: 124 ms


In [23]:
%%time
for i in range(10):
    a = cdist(A, A, metric='sqeuclidean')

CPU times: user 124 ms, sys: 51.5 ms, total: 176 ms
Wall time: 174 ms


In [24]:
%%time
for i in range(10):
    a = pdist(A, metric='sqeuclidean')

CPU times: user 59.7 ms, sys: 12.2 ms, total: 72 ms
Wall time: 70.3 ms


## n = 3000

In [25]:
np.random.seed(0)
A = np.random.rand(3000,3)

In [26]:
%%time
for i in range(10):
    a = distance_2(A)

CPU times: user 1.73 s, sys: 176 ms, total: 1.9 s
Wall time: 1.9 s


In [27]:
%%time
for i in range(10):
    a = cdist(A, A, metric='euclidean')

CPU times: user 568 ms, sys: 152 ms, total: 719 ms
Wall time: 718 ms


In [28]:
%%time
for i in range(10):
    a = pdist(A, metric='euclidean')

CPU times: user 271 ms, sys: 92.1 ms, total: 363 ms
Wall time: 362 ms


In [29]:
%%time
for i in range(10):
    a = cdist(A, A, metric='sqeuclidean')

CPU times: user 321 ms, sys: 148 ms, total: 469 ms
Wall time: 467 ms


In [30]:
%%time
for i in range(10):
    a = pdist(A, metric='sqeuclidean')

CPU times: user 125 ms, sys: 104 ms, total: 228 ms
Wall time: 227 ms
